version: 2.1

orbs:
  cypress: cypress-io/cypress@1.29.0

workflows:
  run_component_tests:
    jobs:
      - cypress/run:
          name: component_tests
          start: npm start
          wait-on: http://localhost:3000
          command: npx cypress run-ct
          executor: cypress/base-14
          no-workspace: true