version: 2.1

orbs:
  cypress: cypress-io/cypress@1.29.0

workflows:
  run_cypress_tests:
    jobs:
      - cypress/run:
          name: component_tests
          start: npm start
          wait-on: http://localhost:3000
          command: npx cypress run-ct
          parallelism: 2 # wont actually split across containers yet
          executor: cypress/base-14
          no-workspace: true
          record: true
      - cypress/run:
          name: e2e_tests
          start: npm start
          wait-on: http://localhost:3000
          parallelism: 2 # wont actually split across containers yet 
          executor: cypress/base-14
          no-workspace: true
          record: true
